service:
  name: <%=name%>

plugins:
  - serverless-webpack
  - serverless-content-encoding
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  profile: <%=aws.profile%>
  memorySize: 128
  timeout: 10
  logRetentionInDays: 1
  stackTags:
    creator: serverless

functions: ${file(./build/functions.js)}
resources: ${file(./build/resources.js)}

package:
  individually: true
  include:
    - lib/**
    - apis/**
  exclude:
    - "node_modules/@types/**"
    - "node_modules/aws-sdk/**"
    - "**/*.ts"

custom:
  webpack:
    includeModules: true
    config: ./webpack.config.js
  serverless-offline:
    port: 3000
<% if (certs) { -%>
    httpsProtocol: dev-certs
<% } else { -%>
    # if you have TLS certs, enable the directory name here and name the files cert.pem and key.pem
    # httpsProtocol: dev-certs
<% } -%>
    dontPrintOutput: true
  iopipeNoVerify: true
  iopipeNoStats: true
  contentEncoding:
    minimumCompressionSize: 1024
